version: '3'
services:
  web:
    container_name: lfi-to-rce-via-log
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1337:80
    volumes:
       - ./src/:/var/www/html/
    image: moeinfatehi/lfi-to-rce-via-log:latest
